{% set version = "2.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-astsa
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/astsa_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/astsa/astsa_{{ version }}.tar.gz
  sha256: a38d9a8be97c18664cd4ac8d2a608f3c34f0e6eb7104a9b5fbd4ae5d3053cb66

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('astsa')"           # [not win]
    - "\"%R%\" -e \"library('astsa')\""  # [win]

about:
  home: https://github.com/nickpoison/astsa/, https://www.stat.pitt.edu/stoffer/tsa4/, https://www.stat.pitt.edu/stoffer/tsda/
  license: GPL-3.0-only
  summary: 'Data sets and scripts to accompany Time Series Analysis and Its Applications: With R Examples (4th ed), by R.H. Shumway and D.S. Stoffer. Springer Texts in Statistics, 2017, <DOI:10.1007/978-3-319-52452-8>, and Time Series:  A Data Analysis Approach Using R. Chapman-Hall, 2019, <ISBN: 978-0367221096>.'
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
